version: '3.8'

services:
  pyload-jellyfin-mover:
    build: .
    container_name: pyload-jellyfin-mover
    ports:
      - "8080:8080"
    volumes:
      - ~/Downloads:/app/Downloads
      - ~/Movies:/app/Movies
      - ~/Series:/app/Series
    environment:
      - FLASK_ENV=production
      - DOWNLOADS_DIR=/app/Downloads
      - MOVIES_DIR=/app/Movies
      - SERIES_DIR=/app/Series
    restart: unless-stopped